import { REDUX_KEY } from 'utils/constants';

export const ACTION_POST_PRODUCTLINE = `${
  REDUX_KEY.homePage
}/ACTION_POST_PRODUCTLINE`;

export const ACTION_BEGIN = `${REDUX_KEY.homePage}/ACTION_BEGIN`;

export const ACTION_END = `${REDUX_KEY.homePage}/ACTION_END`;

export const ACTION_PREPARE_POST_PRODUCT_LINE = `${
  REDUX_KEY.homePage
}/ACTION_PREPARE_POST_PRODUCT_LINE`;

export const ACTION_SEARCH_PRODUCT_LINE_BY_ID = `${
  REDUX_KEY.homePage
}/ACTION_SEARCH_PRODUCT_LINE_BY_ID`;

export const ACTION_DELETE_PRODUCT_LINE_BY_ID = `${
  REDUX_KEY.homePage
}/ACTION_DELETE_PRODUCT_LINE_BY_ID`;

export const ACTION_PUT_PRODUCT_LINE_BY_ID = `${
  REDUX_KEY.homePage
}/ACTION_PUT_PRODUCT_LINE_BY_ID`;

export const ACTION_OPEN_DIALOG = `${REDUX_KEY.homePage}/ACTION_OPEN_DIALOG`;
